# Generated by Django 2.2.19 on 2021-03-15 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import shastra_compedium.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0012_file_mime_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='DanceStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=128)),
                ('contents', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shastra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('author', models.CharField(blank=True, max_length=128, null=True)),
                ('language', models.CharField(blank=True, max_length=128, null=True)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='filer.File')),
            ],
            bases=('filer.file',),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('translation_language', models.CharField(max_length=128)),
                ('translator', models.CharField(max_length=128)),
                ('isbn', models.CharField(max_length=128)),
                ('bibliography', models.TextField(blank=True)),
                ('shastra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='shastra_compedium.Shastra')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='shastra_compedium.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('linneage', models.TextField()),
                ('bio', models.TextField()),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dance_styles', models.ManyToManyField(to='shastra_compedium.DanceStyle')),
                ('image', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExampleVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('dance_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shastra_compedium.DanceStyle')),
                ('details', models.ManyToManyField(to='shastra_compedium.Detail')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shastra_compedium.Performer')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shastra_compedium.Position')),
                ('video', shastra_compedium.models.FilerVideoField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shastra_compedium.Video')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('dance_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shastra_compedium.DanceStyle')),
                ('details', models.ManyToManyField(to='shastra_compedium.Detail')),
                ('image', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shastra_compedium.Performer')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shastra_compedium.Position')),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='sources',
            field=models.ManyToManyField(to='shastra_compedium.Source'),
        ),
        migrations.AddField(
            model_name='category',
            name='sources',
            field=models.ManyToManyField(to='shastra_compedium.Source'),
        ),
        migrations.CreateModel(
            name='PositionDetail',
            fields=[
                ('detail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shastra_compedium.Detail')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shastra_compedium.Position')),
            ],
            bases=('shastra_compedium.detail',),
        ),
        migrations.CreateModel(
            name='CategoryDetail',
            fields=[
                ('detail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shastra_compedium.Detail')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shastra_compedium.Category')),
            ],
            bases=('shastra_compedium.detail',),
        ),
    ]
