# Generated by Django 2.2.19 on 2021-09-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shastra_compedium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shastra',
            name='initials',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='source',
            name='short_form',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
