# Generated by Django 3.0.14 on 2021-10-09 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shastra_compedium', '0002_auto_20210909_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiondetail',
            name='dependencies',
            field=models.ManyToManyField(to='shastra_compedium.PositionDetail'),
        ),
        migrations.AddField(
            model_name='positiondetail',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meaning', to='shastra_compedium.PositionDetail'),
        ),
    ]
