# Generated by Django 3.0.14 on 2021-10-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shastra_compedium', '0003_auto_20211009_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positiondetail',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to='shastra_compedium.PositionDetail'),
        ),
    ]
