# Generated by Django 3.0.14 on 2021-11-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shastra_compedium', '0004_auto_20211023_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampleimage',
            name='general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examplevideo',
            name='general',
            field=models.BooleanField(default=False),
        ),
    ]
