# Generated by Django 3.0.14 on 2021-11-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shastra_compedium', '0005_auto_20211122_0703'),
        ('shastra_compedium', '0005_auto_20211114_0956'),
    ]

    operations = [
    ]
