# Generated by Django 3.0.14 on 2022-06-26 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('shastra_compedium', '0006_merge_20211124_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positiondetail',
            options={'ordering': ['chapter',
                                  'verse_start',
                                  'verse_end',
                                  'id']},
        ),
        migrations.AlterUniqueTogether(
            name='exampleimage',
            unique_together={('image', 'position')},
        ),
        migrations.CreateModel(
            name='CombinationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('usage', models.CharField(max_length=128)),
                ('contents', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('chapter', models.IntegerField(blank=True, null=True)),
                ('verse_start', models.IntegerField(blank=True, null=True)),
                ('verse_end', models.IntegerField(blank=True, null=True)),
                ('positions', models.ManyToManyField(
                    to='shastra_compedium.Position')),
                ('sources', models.ManyToManyField(
                    to='shastra_compedium.Source')),
            ],
            options={
                'ordering': ['chapter', 'verse_start', 'verse_end', 'id'],
            },
        ),
    ]
