# Generated by Django 3.0.14 on 2022-06-30 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shastra_compedium', '0007_auto_20220626_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampleimage',
            name='combinations',
            field=models.ManyToManyField(
                blank=True,
                to='shastra_compedium.CombinationDetail'),
        ),
        migrations.AddField(
            model_name='examplevideo',
            name='combinations',
            field=models.ManyToManyField(
                blank=True,
                to='shastra_compedium.CombinationDetail'),
        ),
        migrations.AlterField(
            model_name='exampleimage',
            name='details',
            field=models.ManyToManyField(
                blank=True,
                to='shastra_compedium.PositionDetail'),
        ),
        migrations.AlterField(
            model_name='exampleimage',
            name='position',
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='shastra_compedium.Position'),
        ),
        migrations.AlterField(
            model_name='examplevideo',
            name='details',
            field=models.ManyToManyField(
                blank=True,
                to='shastra_compedium.PositionDetail'),
        ),
        migrations.AlterField(
            model_name='examplevideo',
            name='position',
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='shastra_compedium.Position'),
        ),
    ]
