# Generated by Django 3.0.14 on 2022-07-01 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shastra_compedium', '0008_auto_20220630_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampleimage',
            name='combinations',
            field=models.ManyToManyField(blank=True, null=True, to='shastra_compedium.CombinationDetail'),
        ),
        migrations.AlterField(
            model_name='exampleimage',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shastra_compedium.Position'),
        ),
        migrations.AlterField(
            model_name='examplevideo',
            name='combinations',
            field=models.ManyToManyField(blank=True, null=True, to='shastra_compedium.CombinationDetail'),
        ),
        migrations.AlterField(
            model_name='examplevideo',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shastra_compedium.Position'),
        ),
    ]
