# Generated by Django 3.0.14 on 2022-07-20 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('shastra_compedium', '0009_auto_20220701_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shastra_compedium.Category')),
            ],
            options={
                'ordering': ['name', 'category'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.AddField(
            model_name='combinationdetail',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shastra_compedium.Subject'),
        ),
        migrations.AddField(
            model_name='exampleimage',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shastra_compedium.Subject'),
        ),
        migrations.AddField(
            model_name='examplevideo',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shastra_compedium.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='exampleimage',
            unique_together={('subject', 'image'), ('image', 'position')},
        ),
    ]
